### GET request to example server
POST http://localhost:5678/webhook-test/update
Content-Type: application/json

{
    "match": "5151e5e4-31bc-4edd-bb97-ed33f5a16996",
    "status": "FULL_TIME",
    "action": "POST"
}
###

POST http://localhost:5678/webhook-test/update
Content-Type: application/json

{
  "match": "5151e5e4-31bc-4edd-bb97-ed33f5a16996",
  "status": "FULL_TIME",
  "action": "STORY"
}
###